set(AX_ENABLE_EXT_LUA OFF CACHE BOOL "Build lua libraries")
set(AX_ENABLE_EXT_GUI OFF CACHE BOOL "Build extension GUI")
set(AX_ENABLE_EXT_ASSETMANAGER OFF CACHE BOOL "Build extension asset-manager")
set(AX_ENABLE_EXT_SPINE OFF CACHE BOOL "Build extension spine")
set(AX_ENABLE_EXT_DRAGONBONES OFF CACHE BOOL "Build extension DragonBones")
set(AX_ENABLE_EXT_COCOSTUDIO OFF CACHE BOOL "Build extension cocostudio")
set(AX_ENABLE_EXT_FAIRYGUI OFF CACHE BOOL "Build extension FairyGUI")
set(AX_ENABLE_EXT_PARTICLE3D OFF CACHE BOOL "Build extension Particle3D")
set(AX_ENABLE_EXT_PHYSICS_NODE OFF CACHE BOOL "Build extension physics-nodes")
set(AX_ENABLE_EXT_INSPECTOR OFF CACHE BOOL "Enable extension Inspector")
set(AX_ENABLE_EXT_SDFGEN OFF CACHE BOOL "Build extension SDFGen")
set(AX_ENABLE_EXT_LIVE2D OFF CACHE BOOL "Build extension Live2D")
set(AX_ENABLE_EXT_EFFEKSEER OFF CACHE BOOL "Build extension Effekseer")
set(AX_ENABLE_EXT_JSONDEFAULT OFF CACHE BOOL "Build extension JSONDefault")

if(ANDROID OR IOS OR TVOS OR WASM)
  set(AX_ENABLE_EXT_IMGUI OFF CACHE BOOL "Build extension ImGui")
else()
  set(AX_ENABLE_EXT_IMGUI ON CACHE BOOL "Build extension ImGui")
endif()

set(AX_ENABLE_3D OFF CACHE BOOL "Build 3D support")
set(AX_ENABLE_3D_PHYSICS OFF CACHE BOOL "Build Physics3D support")
set(AX_ENABLE_NAVMESH OFF CACHE BOOL "Build NavMesh support")
set(AX_ENABLE_PHYSICS OFF CACHE BOOL "Build Physics support")

set(AX_ENABLE_WEBSOCKET OFF CACHE BOOL "Build Websocket client based on yasio")
set(AX_ENABLE_HTTP OFF CACHE BOOL "Build HTTP client based on yasio")
set(AX_ENABLE_MEDIA OFF CACHE BOOL "Build media support")
set(AX_ENABLE_VLC_MEDIA OFF CACHE BOOL "Build libvlc media support")
set(AX_ENABLE_MFMEDIA OFF CACHE BOOL "Build microsoft media foundation support")
set(AX_ENABLE_MSEDGE_WEBVIEW2 OFF CACHE BOOL "Build msedge webview2 support")
set(AX_ENABLE_OPUS OFF CACHE BOOL "Build with opus support")
set(AX_ENABLE_AUDIO ON CACHE BOOL "Build audio support")
